name: Release Drafter

on:
  push:
    tags:
      - '*'

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: default

