[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = "black"

[tool.semantic_release]
branch = "main"
version_source = "tag"
changelog_file = "CHANGELOG.md"
commit_message = "chore(release): {version} [skip ci]\n\n{changelog}"
